import dotenv from 'dotenv';

dotenv.config();

export const {
  DB_NAME,
  DB_USER,
  DB_PASSWORD,
  DB_HOST,
  DB_PORT,
  PORT,
  MP_ACCESS_TOKEN,
  EMAIL,
  PASSWORD_EMAIL,
  FRONTEND_URL,
  BACKEND_URL,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_ID,
  PAYPAL_CLIENT_ID,
  PAYPAL_SECRET,
  PAYPAL_BASE_URL,
  PAYPAL_WEBHOOK_ID,
  SECRET_JWT_SEED,
  KEY_MAIL,
} = process.env;
